### ISSUE TITLE
DISABLED PATIENTS.

### ISSUE THREAD

**Issue by Demma22** [medic/cht-accelerator#31]
Correct this phrase to Disabled Patients.
![Screenshot from 2024-03-27 14-14-54](https://github.com/medic/cht-accelerator/assets/124711625/90c84fec-0903-4721-85d2-2a04120520b0)

**Comment by guildbunny** [comment]
@Demma22 - thanks for this issue - kindly confirm if this is repo where you intended to post it initially.

**Comment by Demma22** [comment]
No this is not where i wanted to post it
